title: Humanshu D G
description: "Humanshu's Portfolio website"
logo: /Pictures/La Energia.png
favicon: true
show_downloads: false
remote_theme: BDHU/minimalist
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
